services:
  db:
    container_name: "apitester-database"
    platform: linux/x86_64
    build:
      context: ..
      dockerfile: deployment/db.Dockerfile
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    restart: always
    env_file:
      - ./.env.db
    expose:
      - "3306"
    volumes:
      - ../resource/db/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend

  api:
    container_name: "apitester-backend"
    build:
      context: ..
      dockerfile: deployment/backend.Dockerfile
    env_file:
      - ../.env.stag
    expose:
      - "8999"
    depends_on:
      - db
    networks:
      - backend
      - frontend


  frontend:
    container_name: apitester-frontend
    build:
      context: ..
      dockerfile: deployment/frontend.Dockerfile
    restart: always
    ports:
      - "8088:8088"
    networks:
      - frontend

networks:
  backend:
  frontend:
