user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    # Additional Setup
    client_max_body_size 4000m;
    server_names_hash_bucket_size 64;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;

    server {
    listen      8088;
    server_name localhost;
    charset utf-8;
   # root     /home/ncteknis/service/pam-ad-web-service/build;
    root    /usr/share/nginx/html/build;
    index   index.html index.htm;
    # Always serve index.html for any request
    location / {
        root /usr/share/nginx/html/build;
        try_files $uri $uri/ /index.html =404;
        }

        error_page 404 /404.html;
                location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
                location = /50x.html {
        }
        error_log  /var/log/nginx/pam-ad-web-error.log;
        access_log /var/log/nginx/pam-ad-web-access.log;
   }
}